### ISSUE TITLE
Configuration and docs

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_onto#2]
It appears from the docs that the intent is to modify the obo's independently from the code, and have users obtain them independently. If this is the case then I think the install docs need to download both wc_onto.obo and kb_onto.obo, and clarify where they go.

On the other hand, core.get_dependent_ontologies() downloads the obo's itself, so perhaps the user doesn't need to.

Please clarify.

**Comment by jonrkarr** [comment]
These are packaged with the code. There is no need for special installation.

**Comment by jonrkarr** [comment]
Done
